fixing error message: 'Learner' object has no attribute 'logger'
When I run `generate_predictions model data.csv`, I get the following

```
Traceback (most recent call last):
  File "c:\programdata\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\programdata\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Anaconda2\Scripts\generate_predictions.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda2\lib\site-packages\skll\utilities\generate_predictions.py", line 167, in main
    for pred in predictor.predict(feature_set):
  File "c:\programdata\anaconda2\lib\site-packages\skll\utilities\generate_predictions.py", line 68, in predict
    preds = self._learner.predict(data)
  File "c:\programdata\anaconda2\lib\site-packages\skll\learner.py", line 1710, in predict
    self.logger.warning("There is mismatch between the training model "
AttributeError: 'Learner' object has no attribute 'logger'
```
Apparently this is because the learner in the model did not have the right logger, for whatever reason. I added a line to pass the root logger to the learner. This works.